version: '3'

services:
  # app:
  #   build: .
  #   entrypoint: ./.docker/entrypoint.sh
  #   container_name: imersao-fullcycle-4-fin-api-app
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - .:/home/node/app
  #   depends_on:
  #     - db

  db:
    build: ./.docker/mysql
    ports:
      - '3306:3306'
    restart: always
    tty: true
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=fin
      - MYSQL_ROOT_PASSWORD=root
